/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java;

import kotleta.App;
import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        System.out.println("ok");
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
